//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPassword.WSPassword {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ClienteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((this.IdClienteField.Equals(value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PasswordDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Password1Field;
        
        private int IdPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password1 {
            get {
                return this.Password1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Password1Field, value) != true)) {
                    this.Password1Field = value;
                    this.RaisePropertyChanged("Password1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdPassword {
            get {
                return this.IdPasswordField;
            }
            set {
                if ((this.IdPasswordField.Equals(value) != true)) {
                    this.IdPasswordField = value;
                    this.RaisePropertyChanged("IdPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSPassword.WebServicePasswordSoap")]
    public interface WebServicePasswordSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GenerarPasswordFacilRecordarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarPasswordFacilRecordar", ReplyAction="*")]
        WebPassword.WSPassword.GenerarPasswordFacilRecordarResponse GenerarPasswordFacilRecordar(WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarPasswordFacilRecordar", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.GenerarPasswordFacilRecordarResponse> GenerarPasswordFacilRecordarAsync(WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GenerarPasswordResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarPassword", ReplyAction="*")]
        WebPassword.WSPassword.GenerarPasswordResponse GenerarPassword(WebPassword.WSPassword.GenerarPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerarPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.GenerarPasswordResponse> GenerarPasswordAsync(WebPassword.WSPassword.GenerarPasswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento clienteRegistro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroUsuario", ReplyAction="*")]
        WebPassword.WSPassword.RegistroUsuarioResponse RegistroUsuario(WebPassword.WSPassword.RegistroUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.RegistroUsuarioResponse> RegistroUsuarioAsync(WebPassword.WSPassword.RegistroUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccesoUsuario", ReplyAction="*")]
        WebPassword.WSPassword.AccesoUsuarioResponse AccesoUsuario(WebPassword.WSPassword.AccesoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccesoUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.AccesoUsuarioResponse> AccesoUsuarioAsync(WebPassword.WSPassword.AccesoUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cliente del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarUsuario", ReplyAction="*")]
        WebPassword.WSPassword.EditarUsuarioResponse EditarUsuario(WebPassword.WSPassword.EditarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EditarUsuarioResponse> EditarUsuarioAsync(WebPassword.WSPassword.EditarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento passwordActual del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        WebPassword.WSPassword.EliminarUsuarioResponse EliminarUsuario(WebPassword.WSPassword.EliminarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EliminarUsuarioResponse> EliminarUsuarioAsync(WebPassword.WSPassword.EliminarUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento passwordRegistro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroPassword", ReplyAction="*")]
        WebPassword.WSPassword.RegistroPasswordResponse RegistroPassword(WebPassword.WSPassword.RegistroPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistroPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.RegistroPasswordResponse> RegistroPasswordAsync(WebPassword.WSPassword.RegistroPasswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AccesoPasswordsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccesoPasswords", ReplyAction="*")]
        WebPassword.WSPassword.AccesoPasswordsResponse AccesoPasswords(WebPassword.WSPassword.AccesoPasswordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccesoPasswords", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.AccesoPasswordsResponse> AccesoPasswordsAsync(WebPassword.WSPassword.AccesoPasswordsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento passwordEdit del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarPasword", ReplyAction="*")]
        WebPassword.WSPassword.EditarPaswordResponse EditarPasword(WebPassword.WSPassword.EditarPaswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarPasword", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EditarPaswordResponse> EditarPaswordAsync(WebPassword.WSPassword.EditarPaswordRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento passwordActual del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPassword", ReplyAction="*")]
        WebPassword.WSPassword.EliminarPasswordResponse EliminarPassword(WebPassword.WSPassword.EliminarPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EliminarPasswordResponse> EliminarPasswordAsync(WebPassword.WSPassword.EliminarPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarPasswordFacilRecordarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarPasswordFacilRecordar", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.GenerarPasswordFacilRecordarRequestBody Body;
        
        public GenerarPasswordFacilRecordarRequest() {
        }
        
        public GenerarPasswordFacilRecordarRequest(WebPassword.WSPassword.GenerarPasswordFacilRecordarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerarPasswordFacilRecordarRequestBody {
        
        public GenerarPasswordFacilRecordarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarPasswordFacilRecordarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarPasswordFacilRecordarResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.GenerarPasswordFacilRecordarResponseBody Body;
        
        public GenerarPasswordFacilRecordarResponse() {
        }
        
        public GenerarPasswordFacilRecordarResponse(WebPassword.WSPassword.GenerarPasswordFacilRecordarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarPasswordFacilRecordarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerarPasswordFacilRecordarResult;
        
        public GenerarPasswordFacilRecordarResponseBody() {
        }
        
        public GenerarPasswordFacilRecordarResponseBody(string GenerarPasswordFacilRecordarResult) {
            this.GenerarPasswordFacilRecordarResult = GenerarPasswordFacilRecordarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarPassword", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.GenerarPasswordRequestBody Body;
        
        public GenerarPasswordRequest() {
        }
        
        public GenerarPasswordRequest(WebPassword.WSPassword.GenerarPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int longitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool numeros;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool simbolos;
        
        public GenerarPasswordRequestBody() {
        }
        
        public GenerarPasswordRequestBody(int longitud, bool numeros, bool simbolos) {
            this.longitud = longitud;
            this.numeros = numeros;
            this.simbolos = simbolos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerarPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerarPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.GenerarPasswordResponseBody Body;
        
        public GenerarPasswordResponse() {
        }
        
        public GenerarPasswordResponse(WebPassword.WSPassword.GenerarPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerarPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerarPasswordResult;
        
        public GenerarPasswordResponseBody() {
        }
        
        public GenerarPasswordResponseBody(string GenerarPasswordResult) {
            this.GenerarPasswordResult = GenerarPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.RegistroUsuarioRequestBody Body;
        
        public RegistroUsuarioRequest() {
        }
        
        public RegistroUsuarioRequest(WebPassword.WSPassword.RegistroUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPassword.WSPassword.ClienteDTO clienteRegistro;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string comprobacion;
        
        public RegistroUsuarioRequestBody() {
        }
        
        public RegistroUsuarioRequestBody(WebPassword.WSPassword.ClienteDTO clienteRegistro, string comprobacion) {
            this.clienteRegistro = clienteRegistro;
            this.comprobacion = comprobacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.RegistroUsuarioResponseBody Body;
        
        public RegistroUsuarioResponse() {
        }
        
        public RegistroUsuarioResponse(WebPassword.WSPassword.RegistroUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistroUsuarioResult;
        
        public RegistroUsuarioResponseBody() {
        }
        
        public RegistroUsuarioResponseBody(string RegistroUsuarioResult) {
            this.RegistroUsuarioResult = RegistroUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccesoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccesoUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.AccesoUsuarioRequestBody Body;
        
        public AccesoUsuarioRequest() {
        }
        
        public AccesoUsuarioRequest(WebPassword.WSPassword.AccesoUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AccesoUsuarioRequestBody() {
        }
        
        public AccesoUsuarioRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccesoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccesoUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.AccesoUsuarioResponseBody Body;
        
        public AccesoUsuarioResponse() {
        }
        
        public AccesoUsuarioResponse(WebPassword.WSPassword.AccesoUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPassword.WSPassword.ClienteDTO AccesoUsuarioResult;
        
        public AccesoUsuarioResponseBody() {
        }
        
        public AccesoUsuarioResponseBody(WebPassword.WSPassword.ClienteDTO AccesoUsuarioResult) {
            this.AccesoUsuarioResult = AccesoUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EditarUsuarioRequestBody Body;
        
        public EditarUsuarioRequest() {
        }
        
        public EditarUsuarioRequest(WebPassword.WSPassword.EditarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPassword.WSPassword.ClienteDTO cliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordActual;
        
        public EditarUsuarioRequestBody() {
        }
        
        public EditarUsuarioRequestBody(WebPassword.WSPassword.ClienteDTO cliente, string passwordActual) {
            this.cliente = cliente;
            this.passwordActual = passwordActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EditarUsuarioResponseBody Body;
        
        public EditarUsuarioResponse() {
        }
        
        public EditarUsuarioResponse(WebPassword.WSPassword.EditarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditarUsuarioResult;
        
        public EditarUsuarioResponseBody() {
        }
        
        public EditarUsuarioResponseBody(string EditarUsuarioResult) {
            this.EditarUsuarioResult = EditarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EliminarUsuarioRequestBody Body;
        
        public EliminarUsuarioRequest() {
        }
        
        public EliminarUsuarioRequest(WebPassword.WSPassword.EliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordActual;
        
        public EliminarUsuarioRequestBody() {
        }
        
        public EliminarUsuarioRequestBody(int idCliente, string passwordActual) {
            this.idCliente = idCliente;
            this.passwordActual = passwordActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EliminarUsuarioResponseBody Body;
        
        public EliminarUsuarioResponse() {
        }
        
        public EliminarUsuarioResponse(WebPassword.WSPassword.EliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarUsuarioResponseBody {
        
        public EliminarUsuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroPassword", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.RegistroPasswordRequestBody Body;
        
        public RegistroPasswordRequest() {
        }
        
        public RegistroPasswordRequest(WebPassword.WSPassword.RegistroPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistroPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPassword.WSPassword.PasswordDTO passwordRegistro;
        
        public RegistroPasswordRequestBody() {
        }
        
        public RegistroPasswordRequestBody(WebPassword.WSPassword.PasswordDTO passwordRegistro) {
            this.passwordRegistro = passwordRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.RegistroPasswordResponseBody Body;
        
        public RegistroPasswordResponse() {
        }
        
        public RegistroPasswordResponse(WebPassword.WSPassword.RegistroPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RegistroPasswordResponseBody {
        
        public RegistroPasswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccesoPasswordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccesoPasswords", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.AccesoPasswordsRequestBody Body;
        
        public AccesoPasswordsRequest() {
        }
        
        public AccesoPasswordsRequest(WebPassword.WSPassword.AccesoPasswordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoPasswordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        public AccesoPasswordsRequestBody() {
        }
        
        public AccesoPasswordsRequestBody(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccesoPasswordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccesoPasswordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.AccesoPasswordsResponseBody Body;
        
        public AccesoPasswordsResponse() {
        }
        
        public AccesoPasswordsResponse(WebPassword.WSPassword.AccesoPasswordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccesoPasswordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPassword.WSPassword.PasswordDTO[] AccesoPasswordsResult;
        
        public AccesoPasswordsResponseBody() {
        }
        
        public AccesoPasswordsResponseBody(WebPassword.WSPassword.PasswordDTO[] AccesoPasswordsResult) {
            this.AccesoPasswordsResult = AccesoPasswordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarPaswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarPasword", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EditarPaswordRequestBody Body;
        
        public EditarPaswordRequest() {
        }
        
        public EditarPaswordRequest(WebPassword.WSPassword.EditarPaswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarPaswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebPassword.WSPassword.PasswordDTO passwordEdit;
        
        public EditarPaswordRequestBody() {
        }
        
        public EditarPaswordRequestBody(WebPassword.WSPassword.PasswordDTO passwordEdit) {
            this.passwordEdit = passwordEdit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarPaswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarPaswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EditarPaswordResponseBody Body;
        
        public EditarPaswordResponse() {
        }
        
        public EditarPaswordResponse(WebPassword.WSPassword.EditarPaswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditarPaswordResponseBody {
        
        public EditarPaswordResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPassword", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EliminarPasswordRequestBody Body;
        
        public EliminarPasswordRequest() {
        }
        
        public EliminarPasswordRequest(WebPassword.WSPassword.EliminarPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passwordActual;
        
        public EliminarPasswordRequestBody() {
        }
        
        public EliminarPasswordRequestBody(int idCliente, string passwordActual) {
            this.idCliente = idCliente;
            this.passwordActual = passwordActual;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebPassword.WSPassword.EliminarPasswordResponseBody Body;
        
        public EliminarPasswordResponse() {
        }
        
        public EliminarPasswordResponse(WebPassword.WSPassword.EliminarPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarPasswordResponseBody {
        
        public EliminarPasswordResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicePasswordSoapChannel : WebPassword.WSPassword.WebServicePasswordSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicePasswordSoapClient : System.ServiceModel.ClientBase<WebPassword.WSPassword.WebServicePasswordSoap>, WebPassword.WSPassword.WebServicePasswordSoap {
        
        public WebServicePasswordSoapClient() {
        }
        
        public WebServicePasswordSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicePasswordSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePasswordSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicePasswordSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.GenerarPasswordFacilRecordarResponse WebPassword.WSPassword.WebServicePasswordSoap.GenerarPasswordFacilRecordar(WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest request) {
            return base.Channel.GenerarPasswordFacilRecordar(request);
        }
        
        public string GenerarPasswordFacilRecordar() {
            WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest inValue = new WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest();
            inValue.Body = new WebPassword.WSPassword.GenerarPasswordFacilRecordarRequestBody();
            WebPassword.WSPassword.GenerarPasswordFacilRecordarResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).GenerarPasswordFacilRecordar(inValue);
            return retVal.Body.GenerarPasswordFacilRecordarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.GenerarPasswordFacilRecordarResponse> WebPassword.WSPassword.WebServicePasswordSoap.GenerarPasswordFacilRecordarAsync(WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest request) {
            return base.Channel.GenerarPasswordFacilRecordarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.GenerarPasswordFacilRecordarResponse> GenerarPasswordFacilRecordarAsync() {
            WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest inValue = new WebPassword.WSPassword.GenerarPasswordFacilRecordarRequest();
            inValue.Body = new WebPassword.WSPassword.GenerarPasswordFacilRecordarRequestBody();
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).GenerarPasswordFacilRecordarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.GenerarPasswordResponse WebPassword.WSPassword.WebServicePasswordSoap.GenerarPassword(WebPassword.WSPassword.GenerarPasswordRequest request) {
            return base.Channel.GenerarPassword(request);
        }
        
        public string GenerarPassword(int longitud, bool numeros, bool simbolos) {
            WebPassword.WSPassword.GenerarPasswordRequest inValue = new WebPassword.WSPassword.GenerarPasswordRequest();
            inValue.Body = new WebPassword.WSPassword.GenerarPasswordRequestBody();
            inValue.Body.longitud = longitud;
            inValue.Body.numeros = numeros;
            inValue.Body.simbolos = simbolos;
            WebPassword.WSPassword.GenerarPasswordResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).GenerarPassword(inValue);
            return retVal.Body.GenerarPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.GenerarPasswordResponse> WebPassword.WSPassword.WebServicePasswordSoap.GenerarPasswordAsync(WebPassword.WSPassword.GenerarPasswordRequest request) {
            return base.Channel.GenerarPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.GenerarPasswordResponse> GenerarPasswordAsync(int longitud, bool numeros, bool simbolos) {
            WebPassword.WSPassword.GenerarPasswordRequest inValue = new WebPassword.WSPassword.GenerarPasswordRequest();
            inValue.Body = new WebPassword.WSPassword.GenerarPasswordRequestBody();
            inValue.Body.longitud = longitud;
            inValue.Body.numeros = numeros;
            inValue.Body.simbolos = simbolos;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).GenerarPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.RegistroUsuarioResponse WebPassword.WSPassword.WebServicePasswordSoap.RegistroUsuario(WebPassword.WSPassword.RegistroUsuarioRequest request) {
            return base.Channel.RegistroUsuario(request);
        }
        
        public string RegistroUsuario(WebPassword.WSPassword.ClienteDTO clienteRegistro, string comprobacion) {
            WebPassword.WSPassword.RegistroUsuarioRequest inValue = new WebPassword.WSPassword.RegistroUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.RegistroUsuarioRequestBody();
            inValue.Body.clienteRegistro = clienteRegistro;
            inValue.Body.comprobacion = comprobacion;
            WebPassword.WSPassword.RegistroUsuarioResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).RegistroUsuario(inValue);
            return retVal.Body.RegistroUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.RegistroUsuarioResponse> WebPassword.WSPassword.WebServicePasswordSoap.RegistroUsuarioAsync(WebPassword.WSPassword.RegistroUsuarioRequest request) {
            return base.Channel.RegistroUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.RegistroUsuarioResponse> RegistroUsuarioAsync(WebPassword.WSPassword.ClienteDTO clienteRegistro, string comprobacion) {
            WebPassword.WSPassword.RegistroUsuarioRequest inValue = new WebPassword.WSPassword.RegistroUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.RegistroUsuarioRequestBody();
            inValue.Body.clienteRegistro = clienteRegistro;
            inValue.Body.comprobacion = comprobacion;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).RegistroUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.AccesoUsuarioResponse WebPassword.WSPassword.WebServicePasswordSoap.AccesoUsuario(WebPassword.WSPassword.AccesoUsuarioRequest request) {
            return base.Channel.AccesoUsuario(request);
        }
        
        public WebPassword.WSPassword.ClienteDTO AccesoUsuario(string email, string password) {
            WebPassword.WSPassword.AccesoUsuarioRequest inValue = new WebPassword.WSPassword.AccesoUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.AccesoUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            WebPassword.WSPassword.AccesoUsuarioResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).AccesoUsuario(inValue);
            return retVal.Body.AccesoUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.AccesoUsuarioResponse> WebPassword.WSPassword.WebServicePasswordSoap.AccesoUsuarioAsync(WebPassword.WSPassword.AccesoUsuarioRequest request) {
            return base.Channel.AccesoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.AccesoUsuarioResponse> AccesoUsuarioAsync(string email, string password) {
            WebPassword.WSPassword.AccesoUsuarioRequest inValue = new WebPassword.WSPassword.AccesoUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.AccesoUsuarioRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).AccesoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.EditarUsuarioResponse WebPassword.WSPassword.WebServicePasswordSoap.EditarUsuario(WebPassword.WSPassword.EditarUsuarioRequest request) {
            return base.Channel.EditarUsuario(request);
        }
        
        public string EditarUsuario(WebPassword.WSPassword.ClienteDTO cliente, string passwordActual) {
            WebPassword.WSPassword.EditarUsuarioRequest inValue = new WebPassword.WSPassword.EditarUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.EditarUsuarioRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.passwordActual = passwordActual;
            WebPassword.WSPassword.EditarUsuarioResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EditarUsuario(inValue);
            return retVal.Body.EditarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EditarUsuarioResponse> WebPassword.WSPassword.WebServicePasswordSoap.EditarUsuarioAsync(WebPassword.WSPassword.EditarUsuarioRequest request) {
            return base.Channel.EditarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.EditarUsuarioResponse> EditarUsuarioAsync(WebPassword.WSPassword.ClienteDTO cliente, string passwordActual) {
            WebPassword.WSPassword.EditarUsuarioRequest inValue = new WebPassword.WSPassword.EditarUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.EditarUsuarioRequestBody();
            inValue.Body.cliente = cliente;
            inValue.Body.passwordActual = passwordActual;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EditarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.EliminarUsuarioResponse WebPassword.WSPassword.WebServicePasswordSoap.EliminarUsuario(WebPassword.WSPassword.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuario(request);
        }
        
        public void EliminarUsuario(int idCliente, string passwordActual) {
            WebPassword.WSPassword.EliminarUsuarioRequest inValue = new WebPassword.WSPassword.EliminarUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.EliminarUsuarioRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.passwordActual = passwordActual;
            WebPassword.WSPassword.EliminarUsuarioResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EliminarUsuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EliminarUsuarioResponse> WebPassword.WSPassword.WebServicePasswordSoap.EliminarUsuarioAsync(WebPassword.WSPassword.EliminarUsuarioRequest request) {
            return base.Channel.EliminarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.EliminarUsuarioResponse> EliminarUsuarioAsync(int idCliente, string passwordActual) {
            WebPassword.WSPassword.EliminarUsuarioRequest inValue = new WebPassword.WSPassword.EliminarUsuarioRequest();
            inValue.Body = new WebPassword.WSPassword.EliminarUsuarioRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.passwordActual = passwordActual;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EliminarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.RegistroPasswordResponse WebPassword.WSPassword.WebServicePasswordSoap.RegistroPassword(WebPassword.WSPassword.RegistroPasswordRequest request) {
            return base.Channel.RegistroPassword(request);
        }
        
        public void RegistroPassword(WebPassword.WSPassword.PasswordDTO passwordRegistro) {
            WebPassword.WSPassword.RegistroPasswordRequest inValue = new WebPassword.WSPassword.RegistroPasswordRequest();
            inValue.Body = new WebPassword.WSPassword.RegistroPasswordRequestBody();
            inValue.Body.passwordRegistro = passwordRegistro;
            WebPassword.WSPassword.RegistroPasswordResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).RegistroPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.RegistroPasswordResponse> WebPassword.WSPassword.WebServicePasswordSoap.RegistroPasswordAsync(WebPassword.WSPassword.RegistroPasswordRequest request) {
            return base.Channel.RegistroPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.RegistroPasswordResponse> RegistroPasswordAsync(WebPassword.WSPassword.PasswordDTO passwordRegistro) {
            WebPassword.WSPassword.RegistroPasswordRequest inValue = new WebPassword.WSPassword.RegistroPasswordRequest();
            inValue.Body = new WebPassword.WSPassword.RegistroPasswordRequestBody();
            inValue.Body.passwordRegistro = passwordRegistro;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).RegistroPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.AccesoPasswordsResponse WebPassword.WSPassword.WebServicePasswordSoap.AccesoPasswords(WebPassword.WSPassword.AccesoPasswordsRequest request) {
            return base.Channel.AccesoPasswords(request);
        }
        
        public WebPassword.WSPassword.PasswordDTO[] AccesoPasswords(int idCliente) {
            WebPassword.WSPassword.AccesoPasswordsRequest inValue = new WebPassword.WSPassword.AccesoPasswordsRequest();
            inValue.Body = new WebPassword.WSPassword.AccesoPasswordsRequestBody();
            inValue.Body.idCliente = idCliente;
            WebPassword.WSPassword.AccesoPasswordsResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).AccesoPasswords(inValue);
            return retVal.Body.AccesoPasswordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.AccesoPasswordsResponse> WebPassword.WSPassword.WebServicePasswordSoap.AccesoPasswordsAsync(WebPassword.WSPassword.AccesoPasswordsRequest request) {
            return base.Channel.AccesoPasswordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.AccesoPasswordsResponse> AccesoPasswordsAsync(int idCliente) {
            WebPassword.WSPassword.AccesoPasswordsRequest inValue = new WebPassword.WSPassword.AccesoPasswordsRequest();
            inValue.Body = new WebPassword.WSPassword.AccesoPasswordsRequestBody();
            inValue.Body.idCliente = idCliente;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).AccesoPasswordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.EditarPaswordResponse WebPassword.WSPassword.WebServicePasswordSoap.EditarPasword(WebPassword.WSPassword.EditarPaswordRequest request) {
            return base.Channel.EditarPasword(request);
        }
        
        public void EditarPasword(WebPassword.WSPassword.PasswordDTO passwordEdit) {
            WebPassword.WSPassword.EditarPaswordRequest inValue = new WebPassword.WSPassword.EditarPaswordRequest();
            inValue.Body = new WebPassword.WSPassword.EditarPaswordRequestBody();
            inValue.Body.passwordEdit = passwordEdit;
            WebPassword.WSPassword.EditarPaswordResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EditarPasword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EditarPaswordResponse> WebPassword.WSPassword.WebServicePasswordSoap.EditarPaswordAsync(WebPassword.WSPassword.EditarPaswordRequest request) {
            return base.Channel.EditarPaswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.EditarPaswordResponse> EditarPaswordAsync(WebPassword.WSPassword.PasswordDTO passwordEdit) {
            WebPassword.WSPassword.EditarPaswordRequest inValue = new WebPassword.WSPassword.EditarPaswordRequest();
            inValue.Body = new WebPassword.WSPassword.EditarPaswordRequestBody();
            inValue.Body.passwordEdit = passwordEdit;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EditarPaswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebPassword.WSPassword.EliminarPasswordResponse WebPassword.WSPassword.WebServicePasswordSoap.EliminarPassword(WebPassword.WSPassword.EliminarPasswordRequest request) {
            return base.Channel.EliminarPassword(request);
        }
        
        public void EliminarPassword(int idCliente, string passwordActual) {
            WebPassword.WSPassword.EliminarPasswordRequest inValue = new WebPassword.WSPassword.EliminarPasswordRequest();
            inValue.Body = new WebPassword.WSPassword.EliminarPasswordRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.passwordActual = passwordActual;
            WebPassword.WSPassword.EliminarPasswordResponse retVal = ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EliminarPassword(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebPassword.WSPassword.EliminarPasswordResponse> WebPassword.WSPassword.WebServicePasswordSoap.EliminarPasswordAsync(WebPassword.WSPassword.EliminarPasswordRequest request) {
            return base.Channel.EliminarPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebPassword.WSPassword.EliminarPasswordResponse> EliminarPasswordAsync(int idCliente, string passwordActual) {
            WebPassword.WSPassword.EliminarPasswordRequest inValue = new WebPassword.WSPassword.EliminarPasswordRequest();
            inValue.Body = new WebPassword.WSPassword.EliminarPasswordRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.passwordActual = passwordActual;
            return ((WebPassword.WSPassword.WebServicePasswordSoap)(this)).EliminarPasswordAsync(inValue);
        }
    }
}
